name: Build project

on:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        Bundle: True
      run: |

    - name: Test
      run: |
        dotnet test ./test/UnitTestEditor --collect:"XPlat Code Coverage"
        dotnet test ./test/UnitTestHoliday --collect:"XPlat Code Coverage"
