name: Package extensions to Nuget

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish to Nuget
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        Bundle: True
      run: |
        dotnet pack src/Extensions/Components/BootstrapBlazor.AzureOpenAI -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.AzureOpenAI.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.AzureSpeech -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.AzureSpeech.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.BaiduOcr -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.BaiduOcr.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.BaiduSpeech -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.BaiduSpeech.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.BarCode -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.BarCode.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.Chart -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Chart.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.CherryMarkdown -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.CherryMarkdown.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.CodeEditor -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.CodeEditor.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.Dock -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Dock.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.FloatingUI -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.FloatingUI.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.FontAwesome -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.FontAwesome.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.Gantt -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Gantt.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.Html2Pdf -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Html2Pdf.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.Live2DDisplay -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Live2DDisplay.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.Markdown -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Markdown.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.MaterialDesign -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.MaterialDesign.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.MaterialDesign.Extensions -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.MaterialDesign.Extensions.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.MouseFollower -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.MouseFollower.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.Splitting -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Splitting.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

        dotnet pack src/Extensions/Components/BootstrapBlazor.SummerNote -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.SummerNote.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.TableExport -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.TableExport.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.Topology -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Topology.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAccess.PetaPoco -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAccess.PetaPoco.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAccess.EntityFrameworkCore -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAccess.EntityFrameworkCore.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAccess.FreeSql -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAccess.FreeSql.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/BootstrapBlazor.TagHelper -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.TagHelper.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Middleware/BootstrapBlazor.Middleware -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Middleware.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
